### ISSUE TITLE
TLS alert unknown CA, with SSL InfoCallback() RET=650

### ISSUE THREAD

**Issue by reischen80** [paullouisageneau/libdatachannel#372] opened 2021-03-17 02:58 UTC
Hi, guys, I run copy-paste example on Windows10 with openssl and libjuice. After sdp negotiation, I got failure as below when copying Offerer candidate info to Answer :

**************************************************************************************************
0: Exit / 1: Enter remote description / 2: Enter remote candidate / 3: Send me
ssage / 4: Print Connection Info *
[Command]: [Gathering State: in-progress]
Local Candidate (Paste this to the other peer after the local description):
a=candidate:1 1 UDP 2122317823 30.211.114.252 53582 typ host

[State: connecting]
[Gathering State: complete]

2
[Candidate]: a=candidate:1 1 UDP 2122317823 30.211.114.252 64697 typ host

0: Exit / 1: Enter remote description / 2: Enter remote candidate / 3: Send me
ssage / 4: Print Connection Info *
[Command]: 2021-03-17 03:11:37.275 ERROR [27404] [rtc::impl::DtlsTransport::Info
Callback@548] DTLS alert: unknown CA(560)
2021-03-17 03:11:37.277 ERROR [27404] [rtc::impl::DtlsTransport::runRecvLoop@525
] DTLS handshake failed
[State: failed]
**************************************************************************************************

I go further into the code generate this log, and found SSL  InfoCallback with para ret is 560, which is not match to any Alert value in Alert Protocol (https://tools.ietf.org/html/rfc5246#section-7.2)

By the way, I ran it successfully on my macbook(macos).
Is there any tips? 
Thanks

**Comment by paullouisageneau** [comment] 2021-03-17 19:18
This alert is sent by the DTLS server side (i.e. the WebRTC peer in passive role) to notify that it rejected the certificate. Is there an error on the other side? A possible scenario is that the offerer rejected the certificate because the copy-pasting of the description broke the fingerprint.

**Comment by reischen80** [comment] 2021-03-18 05:56
I disabled the CA produce by SSL_CTX_set_verify(mCtx, SSL_VERIFY_NONE, NULL) and go through it.

**Comment by paullouisageneau** [comment] 2021-03-18 08:45
> I disabled the CA produce by SSL_CTX_set_verify(mCtx, SSL_VERIFY_NONE, NULL) and go through it.

This means the error indeed comes from `CertificateCallback` rejecting the certificate, which is most probably caused by `PeerConnection::checkFingerprint` rejecting the fingerprint. It's probable that the fingerprint was corrupted when copy-pasting (for instance, a line return might be inserted in the middle due to the console on Windows being very narrow by default).

**Comment by paullouisageneau** [comment] 2021-03-18 19:55
The PR  https://github.com/paullouisageneau/libdatachannel/pull/374 might help you diagnose the issue by showing explicit errors when the fingerprint in description has invalid format.

**Comment by paullouisageneau** [comment] 2021-03-31 16:46
I'm closing this, please re-open if the issue still exists after checking fingerprints.

**Closed by paullouisageneau** 2021-03-31 16:46 UTC
