### ISSUE TITLE
Improve the throughput systematically

### ISSUE THREAD

**Issue by ptesavol** [paullouisageneau/libdatachannel#409] opened 2021-04-15 15:07 UTC
We have now extended our [node-datachannel benchmarking tool](https://github.com/streamr-dev/node-datachannel-performance-diagnostics/tree/main/benchmark)
to also support libdatachannel tests. Here are results from a run on a physical Linux machine:

### Node-datachannel (Ubuntu 20.04 on a physical machine) 

| Message size(bytes)  | ping RTT (ms) | Netperf TCP throughput (Mbit/s) | node-datachannel throughput (Mbit/s) | Percent of TCP throughput |
|----------------------|---------------|---------------------------------|--------------------------------------|---------------------------|
| 262144               | 0	           | 13540.24	                     | 416.00                               | 3.072323681               | 
| 262144               | 12	           | 2035.23	                     | 208.77                               | 10.2578087                |
| 262144               | 20	           | 1193.27                         | 208.92                               | 17.50819178               | 
| 262144               | 52	           | 407.74                          | 52.43                                | 12.85868446               | 
| 262144               | 100	       | 227.85                          | 46.63                                | 20.46521835               |
| 262144               | 200	       | 101.80                          | 17.63                                | 17.31827112               |
| 262144	           | 500	       | 29.77                           | 12.18                                | 40.91367148               |

### Libdatachannel (Ubuntu 20.04 on a physical machine)

| Message size(bytes) | ping RTT (ms) | Netperf TCP throughput (Mbit/s) | libdatachannel throughput (Mbit/s)   | Percent of TCP throughput |
|---------------------|---------------|---------------------------------|--------------------------------------|---------------------------|
| 262144              | 0             | 13919.38                        | 441.363937                           | 3.17086                   |
| 262144              | 12            | 2040.04                         | 273.335435                           | 13.3985                   |
| 262144              | 20            | 1220.10                         | 155.246328                           | 12.7241                   |
| 262144              | 52            | 439.25                          | 66.718995                            | 15.1893                   |
| 262144              | 100           | 228.93                          | 31.264873                            | 13.657                    |
| 262144              | 200           | 102.54                          | 19.488989                            | 19.0062                   |
| 262144              | 500           | 29.22                           | 10.623808                            | 36.358                    |

The results indicate that achieved throughput is overall very low compared to TCP throughput, and that
there is no significant difference in the throughput of node-datachannel compared to that of libdatachannel.  

In order to improve the throughput, it might be worthwhile to try to systematicallty locate the bottleneck to be able to fix it. 

We drafted a decision tree below shown below that could be used in narrowing down the source of the low throughput:

```
        _______________________  
       | 1. Is the problem in  |
       | node-datachannel      | 
       | or libdatachannel?    |
       |_______________________|                
          /              \
    node-datachannel   libdatachannel
        /                  \
       /                    \ 
     (X)         _______________________
                | 1.2 Is the problem in |
                |    usrsctp?           |
                |_______________________|
                      /     	    \
                    yes     	    no
                    /                 \   
                   /                   \ 
         ______________________      ____________________________
        | 1.2.1 Is it a        |    | 1.2.2 Find and fix         |
        | configuration issue? |    | problem in libdatachannel! |
        |______________________|    |____________________________|
                 /       \
               yes       no
               /           \
              /             \          
 ___________________       _______________________   
| 1.2.1.1 Find the  |     | 1.2.1.2 Is it a CRC   |
| best config! 	    |     | issue?                |
|___________________|     |_______________________| 
                              /	            \	
                            yes             no
                            /	              \
                           /	               \
         ___________________           ________________________	   
        | 1.2.1.2.1 Offload |         | 1.2.1.2.2 Replace      | 
        | CRC calculations! |         | usrsctp with something | 
        |                   |         | else!                  | 
        |___________________|         |________________________|

```

The decision tree has four questions, one of which we already have answer to, and the rest require some
experimenting to resolve:

### 1. Is the problem in node-datachannel or libdatachannel?

The problem is in libdatachannel, because the benchmarks show similar performance.

### 1.2 Is the problem in usrsctp?

This question can be answered by running a pure usrsctp benchmark in our emulated network, and comparing the results to those of libdatachannel. If I remember correctly, there was such a benchmark the usrsctp repository somewhere? 

### 1.2.1 Is it a configuration issue?

This question can be answered by exploring the usrsctp parameter space that now can be accessed using the new API, and
by running the benchmark after each change.

### 1.2.1.2 Is it a CRC issue?

This question can be answered by temporarily turning off the CRC checking and generation using [the CRC offloading API of usrsctp](https://github.com/sctplab/usrsctp/blob/master/programs/ekr_loop_upcall.c), and benchmarking if this has a significant effect on throughput. 

    
There is a lot of work to be done here, but the throughput issue is an important on in the Streamr use case where we use WebRTC not only to connect to browsers but also between nodes running in datacenters. 

@paullouisageneau if you are interested in / have time to work on improving the throughput, maybe we could have a conference call to synchronize our efforts?

**Comment by paullouisageneau** [comment] 2021-04-15 21:29
Very interesting, thanks for all the work you did so far!

Here are some first thoughts:
- It's a bit weird to compare WebRTC data channels to plain TCP, as they run over SCTP + DTLS. Since DTLS adds significant processing and overhead, it would be better to compare it to TLS over TCP (an HTTPS transfer, for instance).

- During your tests, it would be interesting to know if the CPU is a limiting factor or not (by checking if a core is running at 100% at any given time). If it is, some profiling with valgrind could help determining is the CPU bottleneck is in usrsctp or not. If it is not, then running usrsctp alone might be the best approach.

- 400 Mbit/s with 0 ms RTT is quite low. I get at least 1200 Mbit/s when benchmarking locally on my desktop (CPU is the bottleneck). Are you sure you build is optimized? I guess the default cmake build type will rely on system defaults and is probably not optimized, instead the library should be build with `cmake -B build -DCMAKE_BUILD_TYPE=Release`. @murat-dogan do you do that for node-datachannel?

- I don't think CRC is a likely culprit, as encryption/decryption for DTLS alone is much heavier on CPU for instance. Do you run the tests with GnuTLS or OpenSSL?

**Comment by murat-dogan** [comment] 2021-04-16 06:11
Hi @paullouisageneau ,

I am using [cmake-js](https://github.com/cmake-js/cmake-js) and default build is Release.

Some Notes
- As I understood, @ptesavol is using word RTT as virtual latency not usrsctp RTT. (In this scenario SCTP RTT is ~5ms)
- If you compare `libdatachannel` results with [rawrtc results](https://docs.google.com/spreadsheets/d/1Ze2hZl9KZJ1hKcm5Y9J0OIknQCBHUpw5eefskCc8xpM/edit#gid=1018548570), it is quite good! 
- For 0 latency, limit is CPU.

**Comment by ptesavol** [comment] 2021-04-16 12:04
Hi @paullouisageneau here are some comments:

> * It's a bit weird to compare WebRTC data channels to plain TCP, as they run over SCTP + DTLS. Since DTLS adds significant processing and overhead, it would be better to compare it to TLS over TCP (an HTTPS transfer, for instance).

The TCP throughput measurement is made to find out the maximum throughput of the emulated link. I agree that we should also measure the impact of DTLS on the throughput. I noticed that @reischen80 is working to turn off DTLS in issue https://github.com/paullouisageneau/libdatachannel/issues/399 If this was successful, we could be able to make the measurement that determines how much the throughput is limited by DTLS

> * During your tests, it would be interesting to know if the CPU is a limiting factor or not (by checking if a core is running at 100% at any given time). If it is, some profiling with valgrind could help determining is the CPU bottleneck is in usrsctp or not. If it is not, then running usrsctp alone might be the best approach.

We have been looking at the CPU load using htop while running the tests and it seems that CPU usage is very high only at the lowest latencies. Of course, staring at htop is a very inaccurate method of determining CPU usage. Would some more accurate method of determining CPU load non-interactively come to your mind?

> * 400 Mbit/s with 0 ms RTT is quite low. I get at least 1200 Mbit/s when benchmarking locally on my desktop (CPU is the bottleneck). Are you sure your build is optimized? I guess the default cmake build type will rely on system defaults and is probably not optimized, instead the library should be build with `cmake -B build -DCMAKE_BUILD_TYPE=Release`. @murat-dogan do you do that for node-datachannel?

We also compile the libdatachannel test with "cmake -B build -DCMAKE_BUILD_TYPE=Release"

> * I don't think CRC is a likely culprit, as encryption/decryption for DTLS alone is much heavier on CPU for instance. Do you run the tests with GnuTLS or OpenSSL?

We used GnuTLS

**Comment by ptesavol** [comment] 2021-04-16 12:06
@murat-dogan 
> * As I understood, @ptesavol is using word RTT as virtual latency not usrsctp RTT. (In this scenario SCTP RTT is ~5ms)

Yes, the RTT in the table is the measured ping of the emulated link.

**Comment by paullouisageneau** [comment] 2021-04-16 19:59
> I am using [cmake-js](https://github.com/cmake-js/cmake-js) and default build is Release.
>
> We also compile the libdatachannel test with "cmake -B build -DCMAKE_BUILD_TYPE=Release"

Excellent! 

So I think there are two different issues: CPU caps the throughput at lower RTTs, and something else caps it at higher ones. 

@ptesavol Did you already try changing SCTP buffer sizes? Currently they are 1MB, so the maximum theoretical throughput is 200 Mbit/s for a 50ms SCTP RTT, not counting any overhead.

> We have been looking at the CPU load using htop while running the tests and it seems that CPU usage is very high only at the lowest latencies. Of course, staring at htop is a very inaccurate method of determining CPU usage. Would some more accurate method of determining CPU load non-interactively come to your mind?

I don't think it's very useful to measure the precise CPU load, it's only a rule of thumb method: if one core runs near 100% during a transfer, you can assume there is a CPU bottleneck. I just ran a quick benchmark in callgrind: to sum up, it appears 30-40% of instructions are spent in GnuTLS encryption/decryption, a sizeable chunk are also spent in usrsctp but CRC32 represents only 15%. It appears a non-negligible 5% is spent on allocations of messages in libdatachannel, which could be highly optimized with a memory pool, which means there is some margin to reduce CPU cost.

**Comment by ptesavol** [comment] 2021-04-20 12:10
I just ran the benchmark with the dtls-disabled version of dtlstransport.cpp posted by @reischen80 in issue https://github.com/paullouisageneau/libdatachannel/issues/399.

The improvement achieved by disabling dtls seems to be marginal. Here are the the results:

| Message size(bytes) | ping RTT (ms) | Netperf TCP throughput (Mbit/s) | libdatachannel throughput (Mbit/s)   | Percent of TCP throughput |
|---------------------|---------------|---------------------------------|--------------------------------------|---------------------------|
| 262144             | 0      | 14311.76               | 562.907922                           | 3.93318                   |
| 262144             | 12      | 2038.79               | 274.478169                           | 13.4628                   |
| 262144             | 20      | 1216.67               | 211.956705                           | 17.4211                   |
| 262144             | 52      | 428.62               | 92.788429                           | 21.6482                   |
| 262144             | 100      | 227.93               | 33.223753                           | 14.5763                   |
| 262144             | 200      | 103.04               | 15.272244                           | 14.8217                   |
| 262144             | 500      | 29.60               | 6.566396                           | 22.1838                   |

My guess is that disabling dtls has little effect because of the [AES instruction set](https://en.wikipedia.org/wiki/AES_instruction_set) being available on modern processors.

**Comment by paullouisageneau** [comment] 2021-04-20 13:04
It looks like CPU starts being the bottleneck only for very high throughput. When the RTT is higher, something else is limiting the throughput.

The usual suspects are the maximun window size (limited by the buffer size) and the congestion control algorithm. Did you try increasing SCTP buffer sizes, for instance to 2 or 4 MB?

**Comment by ptesavol** [comment] 2021-04-20 14:15
I tried increasing the buffers to 5M by doing

SctpSettings settings;
settings.recvBufferSize = 1024 * 1024 * 5;
settings.sendBufferSize = 1024 * 1024 * 5;
rtc::SetSctpSettings(settings);

This didn't seem to improve the throughput:


| Message size(bytes) | ping RTT (ms) | Netperf TCP throughput (Mbit/s) | libdatachannel throughput (Mbit/s)   | Percent of TCP throughput |
|---------------------|---------------|---------------------------------|--------------------------------------|---------------------------|
| 262144             | 0      | 15148.89               | 429.790643                           | 2.83711                   |
| 262144             | 12      | 2042.19               | 383.053221                           | 18.757                   |
| 262144             | 20      | 1218.99               | 230.420576                           | 18.9026                   |
| 262144             | 52      | 435.69               | 50.929063                           | 11.6893                   |
| 262144             | 100      | 211.44               | 21.783776                           | 10.3026                   |
| 262144             | 200      | 104.55               | 2.901961                           | 2.77567                   |
| 262144             | 500      | 29.36               | 8.712620                           | 29.6751                   |

**Comment by paullouisageneau** [comment] 2021-04-20 14:39
Hum, the throughput increased by a whopping 40% when the RTT is 12 ms but that's about it. I guess ~ 400 Mbit/s reaches the same CPU limits as when RTT is 0, so it's really encouraging actually.

The values for higher RTTs are a bit lower, this could indicate usrsctp overflows a buffer lower in the stack, probably the UDP socket buffer. The potential problem is that by default usrsctp does not limit packet bursts, and the UDP buffer is only set to 1 MB. I think it's worth adding a max burst (and a setting for it).

**Comment by ptesavol** [comment] 2021-04-20 14:46
> The values for higher RTTs are a bit lower, this could indicate usrsctp overflows a buffer lower in the stack, probably the UDP socket buffer. The potential problem is that by default usrsctp does not limit packet bursts, and the UDP buffer is only set to 1 MB. I think it's worth adding a max burst (and a setting for it).

Would this be difficult to do? Does usrsctp offer an API for doing this? One thing we could try first could be increasing the UDP buffers on the Linux machine where the tests are run, and observing whether this increases the throughput.

**Comment by paullouisageneau** [comment] 2021-04-20 14:58
> Would this be difficult to do? Does usrsctp offer an API for doing this?

No it's not difficult, there is indeed an API for this.

> One thing we could try first could be increasing the UDP buffers on the Linux machine where the tests are run, and observing whether this increases the throughput.

Yes good idea, however the maximum buffer size of linux is not sufficient, you might also have to increase the buffer size manually in libjuice: https://github.com/paullouisageneau/libjuice/blob/f9720541ae5c7319760add3ad1ddcf752af55264/src/udp.c#L112

**Comment by ptesavol** [comment] 2021-04-20 14:58
Ok, now this is getting interesting. After setting 

SctpSettings settings;
settings.recvBufferSize = 1024 * 1024 * 10;
settings.sendBufferSize = 1024 * 1024 * 10;
rtc::SetSctpSettings(settings);

also the 20ms throughput jumps up:

| Message size(bytes) | ping RTT (ms) | Netperf TCP throughput (Mbit/s) | libdatachannel throughput (Mbit/s)   | Percent of TCP throughput |
|---------------------|---------------|---------------------------------|--------------------------------------|---------------------------|
| 262144             | 0      | 16150.84               | 424.033438                           | 2.62546                   |
| 262144             | 12      | 2040.93               | 321.851152                           | 15.7698                   |
| 262144             | 20      | 1200.84               | 344.238676                           | 28.6665                   |
| 262144             | 52      | 402.02               | 81.205495                           | 20.1994                   |
| 262144             | 100      | 227.25               | 8.560454                           | 3.76698                   |
| 262144             | 200      | 103.62               | 16.587314                           | 16.0078                   |
| 262144             | 500      | 29.43               | 8.173273                           | 27.7719                   |

**Comment by paullouisageneau** [comment] 2021-04-20 17:32
Great, very interesting! A bigger buffer is definitely key, even if there is still this phenomenon for the throughput drops for higher RTTs.

Setting a max burst might help, you can try with https://github.com/paullouisageneau/libdatachannel/pull/414. By default it sets the max burst to 10 packets.

**Comment by ptesavol** [comment] 2021-04-20 17:39
What do you think would be a good max burst value to try, considering the message size of 262144, the buffer size of libjuice and the default UDP buffer size of Ubuntu 20.04?

**Comment by paullouisageneau** [comment] 2021-04-20 18:42
> What do you think would be a good max burst value to try, considering the message size of 262144, the buffer size of libjuice and the default UDP buffer size of Ubuntu 20.04?

The maximum buffer size on most Linux systems is 200KB, so let's say 100KB actionable (half the space is supposed to be for bookkeeping overhead), which is roughly 80 MTU (the MTU is 1280 by default in libdatachannel), so I think you can try setting the max burst to a conservative 40 to target half the buffer. Then you might also try 10 (the default in the PR, which seems a sensible value). FYI the former behavior without a max burst corresponds to value -1 in the C API.

**Comment by paullouisageneau** [comment] 2021-05-07 19:16
@ptesavol Did you have time to look into it?

**Comment by reischen80** [comment] 2021-05-10 13:32
@ptesavol @paullouisageneau   Did you guys have any result on end-to-end latency comprison between TCP and SCTP ?   I use Clumsy to simulate  poor network situation and find SCTP is more sensitive to  packet lost compared to packet lagging. When lost rate comes to 10%, latency becomes worse.

E2E latency(ms) At transfers 64bytes every 16ms: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Lagging      (ms) | Lost rate     (0-1) | TCP | SCTP
-- | -- | -- | --
50 | 0 | 205 | 99
300 | 0 | 1023 | 350
50 | 0.02 | 227 | 124
50 | 0.05 | 257 | 156
50 | 0.1 | 308 | 231



</body>

</html>


E2E latency(ms) At transfers 1024bytes every 16ms: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Lagging      (ms) | Lost rate     (0-1) | TCP | SCTP
-- | -- | -- | --
50 | 0 | 140 | 100
300 | 0 | 520 | 380
50 | 0.02 | 154 | 147
50 | 0.05 | 199 | 288
50 | 0.1 | 333 | 3038



</body>

</html>


When  I  use usrsctp_sysctl_set_sctp_default_cc_module(SCTP_CC_HTCP) , the latency even worse.
What SCTP configuration can lead to better e2e latency at deference network?

**Comment by paullouisageneau** [comment] 2021-05-10 17:06
Interesting, I'm surprised 1024 bytes vs 64 bytes bytes makes that much of a difference, both fit in a packet given the MTU, and 1024 bytes every 16ms is only 64 KB/s. How many latency measurements did you average to get the results?

> When I use usrsctp_sysctl_set_sctp_default_cc_module(SCTP_CC_HTCP) , the latency even worse.

I'm not surprised, I suspect that the HTCP implementation in usrsctp is broken, see https://github.com/paullouisageneau/libdatachannel/issues/354. Only the default congestion control seems to be well tested.

**Comment by paullouisageneau** [comment] 2021-05-11 08:15
> Here is my SCTP config:
> 
> [sctptransport.cpp.txt](https://github.com/paullouisageneau/libdatachannel/files/6455856/sctptransport.cpp.txt)

You seem to use version 0.12 or earlier, could you please try with version 0.13? There were some changes in SCTP settings, and there is now an external API to change the settings:
https://github.com/paullouisageneau/libdatachannel/blob/945749216978450d7559a39c690a8c1bbd00e6f3/include/rtc/global.hpp#L59

**Comment by reischen80** [comment] 2021-05-20 03:07
I update the SCTP latest default setting in version 0.13 and nothing improve. The result is slightly different due to the network situation. 

And then I tested another tiny ARQ library  [KCP](https://github.com/skywind3000/kcp) which also aim to the low latency tiny data transfermation. It seems KCP in fast mode outperform SCTP and TCP in both 64B and 1024B every 16ms.
According to my understanding, KCP has serveral key features: 1) FastResend (configurable RTO time); 2) UNA/ACK mechnism (Compared to SACK in SCTP) ; 3) Streammode (packets in one MTU) , which is also supported by SCTP.  So I think there might be some other setting to imporve the latency of tiny data transfermation.

Here is the results:





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/jiada/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





64 Bytes | &nbsp; | &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | -- | --
Lagging     &nbsp;(ms) | Lost rate     (0-1) | TCP | SCTP | KCP
50 | 0 | 205 | 99 | 75
300 | 0 | 1023 | 350 | 332
50 | 0.02 | 227 | 124 | 82
50 | 0.05 | 257 | 156 | 94
50 | 0.1 | 308 | 231 | 107
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
256 Bytes | &nbsp; | &nbsp; | &nbsp; | &nbsp;
Lagging     &nbsp;(ms) | Lost rate     (0-1) | TCP | SCTP | KCP
50 | 0 | 206 | 102 | 72
300 | 0 | 560 | 352 | 325
50 | 0.02 | 264 | 139 | 87
50 | 0.05 | 269 | 161 | 92
50 | 0.1 | 361 | 191 | 117
&nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp;
1024 Bytes | &nbsp; | &nbsp; | &nbsp;
Lagging     &nbsp;(ms) | Lost rate     (0-1) | TCP | SCTP | KCP
50 | 0 | 140 | 100 | 70
300 | 0 | 520 | 380 | 325
50 | 0.02 | 154 | 147 | 81
50 | 0.05 | 199 | 288 | 86
50 | 0.1 | 333 | 3038 | 116

**Comment by paullouisageneau** [comment] 2021-05-20 12:37
> And then I tested another tiny ARQ library [KCP](https://github.com/skywind3000/kcp) which also aim to the low latency tiny data transfermation. It seems KCP in fast mode outperform SCTP and TCP in both 64B and 1024B every 16ms.
> According to my understanding, KCP has serveral key features: 1) FastResend (resend immediatly when future pkt ack recevied); 2) UNA/ACK mechnism (Compared to SACK in SCTP) ; 3) Streammode (packets in one MTU), which is also supported by SCTP. So I think there might be some other setting to imporve the latency of tiny data transfermation.

Both TCP and SCTP have the same features (TCP also has SACK). However, the default settings are typically not aggressive to prevent network congestion.

If I understand correctly, the issue is with 1024 bytes when the loss rate increases, right?

The PR https://github.com/paullouisageneau/libdatachannel/pull/426 reduces the minimum retransmission timeout to 200ms to match Linux TCP, and exposes retransmission timeout settings, you might in particular want to reduce `minRetransmissionTimeout` even more.

**Comment by paullouisageneau** [comment] 2021-10-14 16:43
As I don't see more addressable opportunities for improvement, I'm closing this issue. Feel free to re-open it to suggest performance enhancements or report low performance scenarios.

**Closed by paullouisageneau** 2021-10-14 16:43 UTC
Labels: enhancement
