### ISSUE TITLE
Peer connect hangs in 32bits on Windows.

### ISSUE THREAD

**Issue by Nemirtingas** [paullouisageneau/libdatachannel#190] opened 2020-09-26 17:20 UTC
Hi,

I've got a strange behavior, when testing my app with libdatachannel.
If both clients are 64bits, it works, I can create rtc::PeerConnection and after some time, their respective rtc::PeerConnection::State is Connected.
But if 1 client is 64bits and the other is 32bits, the 64bits can connect to the 32bits client and its state is Connected but the 32bits peer is stuck Connecting.
If both clients are 32bits, they are both stuck at Connecting.

Here are 2 logs, 1 for 64bits client and 1 for 32bits client. They are both from the same test.
On the 32bits client, the rtc::PeerConnection::onStateChange is only triggered for rtc::PeerConnection::State::Connecting and it never trigger onDataChannel. On the 64bits clients, it works fine.

Any Idea ?
I'm using libdatachannel v0.9.0 and libjuice v0.4.6.

[not_working_x86.log](https://github.com/paullouisageneau/libdatachannel/files/5287073/not_working_x86.log)
[working_x64.log](https://github.com/paullouisageneau/libdatachannel/files/5287074/working_x64.log)

**Comment by paullouisageneau** [comment] 2020-09-26 18:28
It seems the SCTP association never changes to connected, which hints at an issue with usrsctp. Could you update to libdatachannel v0.9.2 (in which usrsctp has been updated) and update the submodules to see if the issue is still present?

If the issue is still there after updating, could you please get the verbose log of the 32-bit client?

**Comment by Nemirtingas** [comment] 2020-09-26 18:40
Gonna try, brb in like 10mins.

**Comment by Nemirtingas** [comment] 2020-09-26 19:25
Still not working :'(. Here's the verbose logs.

[not_working_32bits.log](https://github.com/paullouisageneau/libdatachannel/files/5287206/not_working_32bits.log)
[working_x64.log](https://github.com/paullouisageneau/libdatachannel/files/5287208/working_x64.log)

**Comment by paullouisageneau** [comment] 2020-09-26 22:26
Are you sure the 32-bit one does not work here? In the log there is:
```
2020-09-26 21:16:42.974 INFO  [3384] [rtc::SctpTransport::processNotification@609] SCTP connected
```
This wasn't present in the previous log, and it means the peer connection state should change to Connected. Isn't it the case? Also, the data channel ACK is going through, which means the data channel might open. Do you confirm it doesn't for the 32-bit run?

**Comment by Nemirtingas** [comment] 2020-09-26 23:05
Hmm, I'll re-check... Tomorrow ;).

**Comment by Nemirtingas** [comment] 2020-09-27 10:44
I create 2 data channels,
1 reliable for control transmition
`dc = peer.pc->createDataChannel(label);`
1 unreliable for data transmition.
`dc = peer.pc->createDataChannel(label, "", rtc::Reliability{rtc::Reliability::Type::Rexmit, false, 0});`

When I received a peer list for my signalling server, I do the following:
createPeerConnection(peer_id);
createDataChannel(peer_id, "reliable_channel");
createDataChannel(peer_id, "unreliable_channel");

The reliable is created and is connected (onOpen), but the unreliable is stuck inside the createDataChannel function and never returns.
Its even worst now that I updated, my 64bits code doesn't work anymore.

**Comment by paullouisageneau** [comment] 2020-09-27 10:51
OK, what do you mean by `stuck inside the createDataChannel function`? Does the function never return?

**Comment by Nemirtingas** [comment] 2020-09-27 10:54
> 
> 
> OK, what do you mean by "stuck inside the createDataChannel function"? Does the function never return?

Exactly, it nevers returns.

**Comment by Nemirtingas** [comment] 2020-09-27 11:01
peerconnection.cpp L265: PeerConnection::createDataChannel
peerconnection.cpp L112: PeerConnection::setLocalDescription
peerconnection.cpp L731: PeerConnection::processLocalDescription
peerconnection.cpp L735: throws the exception.

**Comment by paullouisageneau** [comment] 2020-09-27 11:16
OK, I found the issue, the second call to `setLocalDescription` is supposed to be ignored but a return is missing in `peerconnection.cpp` line 105. It should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/192

**Comment by Nemirtingas** [comment] 2020-09-27 11:18
Many thanks.

**Closed** 2020-09-27 11:42 UTC
