### ISSUE TITLE
Visual Studio option for c++17 causes "byte ambiguous symbol" error.

### ISSUE THREAD

**Issue by mehmetcy84** [paullouisageneau/libdatachannel#739] opened 2022-11-11 10:55 UTC
I am using VS 2017 and I want to incorporate libdatachannel as a lib to my existing project. In order to fix the compile errors coming from c++17 usage, I needed to add /std:c++17 to C/C++>All Options>Additional options.

But with this addition, when I attempt to build my project with libdatachannel lib added (I also added the media-receiver sample main code block into my project) I receive these errors:

1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\rpcndr.h(962): error C2872: 'byte': ambiguous symbol
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\wtypesbase.h(461): error C2872: 'byte': ambiguous symbol
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\wtypes.h(98): error C2872: 'byte': ambiguous symbol
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\objidlbase.h(2189): error C2872: 'byte': ambiguous symbol

Has there been any other report for this issue, and do you know of a remedy for this?
Thanks in advance,

**Comment by paullouisageneau** [comment] 2022-11-11 11:36
I'm not sure this is a libdatachannel issue. It looks like there is a conflict between `std::byte` from C++ 17 and `byte` defined by Microsoft Windows headers. However, I think it could happen only if there is a `using namespace std`, `using namespace rtc`, or `using std::byte` directive *before* including Windows headers. Is that the case?

**Comment by mehmetcy84** [comment] 2022-11-11 12:11
Exactly! In one of the classes in this large existing project, here was the case:
using namespace std;
#include "pthread.h"
#include "semaphore.h"
#include "Winsock2.h"
#include "Windows.h"

And when I moved using line under the includes, the issue is resolved. So, what is the reasoning behind this? And thanks for the quick reply and help again.

**Comment by paullouisageneau** [comment] 2022-11-13 09:21
The issue is that, since `using namespace std` imports the entire `std` namespace into the top-level one, it is like defining stuff there, including the new `byte`  type from C++17, then Windows headers also define `byte` so `byte` is ambiguous because of the name collision. In general, you should not define anythng before including headers as it may cause such issues.

I'm closing this as it is resolved.

**Closed by paullouisageneau** 2022-11-13 09:21 UTC
