### ISSUE TITLE
Sending large number of messages through DataChannel

### ISSUE THREAD

**Issue by sriramsk1999** [paullouisageneau/libdatachannel#231] opened 2020-11-04 16:30 UTC
Hello, I'm using libdatachannel to transmit audio/video from a video game to the client as a binary (`std::vector<byte>`). As a test run, I had a call to `dc->send("Hello")` for every iteration of the game loop. However, after around 30 seconds of the DataChannel starting to send messages, the DataChannel abrubtly closes. Are DataChannels not meant for this kind of communication, or am I doing something wrong here?

The log for the run is [here](https://github.com/sriramsk1999/llft-gaas/blob/master/logs/log.txt). The relevant source code is under [`dc->onOpen()`](https://github.com/sriramsk1999/llft-gaas/blob/master/src/main.cpp#L168). Do let me know if any other information is to be provided.

**Comment by paullouisageneau** [comment] 2020-11-04 20:30
I think there are two distinct issues here: you shouldn't just send at a fixed high rate in a Data Channel, but it should not close as a result.

About sending data at a fixed high rate: you might easily run into problems after some time if the network or the remote side are unable to process the messages fast enough. In that case, the Data Channel will send only as fast as it may and buffer data before sending it, which will introduce a delay and take some memory. You don't want the Data Channel buffer to grow out of control, so you have two options:
- If you accept to lose messages, you should check `bufferedAmount()` before sending and drop messages if necessary.
- If you don't want to lose messages, you should stop sending when `bufferedAmount()` increases and resume sending when the callback `onBufferedAmountLow()` is called.

About the Data Channel abruptly closing: do you try to send at the same rate from the other side, by any chance? libdatachannel shouldn't close when too much data is buffered, but the browser implementation will.

**Comment by sriramsk1999** [comment] 2020-11-05 04:13
So I ran a few tests, checking `bufferedAmount()` after every call to `dc->send()`. 
- When sending just the "Hello" string, the bufferedAmount remained zero until the second the channel closed, it did not increase.
- When sending audio (1kB binary), the bufferedAmount was zero initially but soon climbed all the way to 120k before the DataChannel closed. 

> About the Data Channel abruptly closing: do you try to send at the same rate from the other side, by any chance? libdatachannel shouldn't close when too much data is buffered, but the browser implementation will.

There is no data being sent from the other side, so I'm fairly certain there is no problem with the client.

**Comment by paullouisageneau** [comment] 2020-11-05 19:26
> So I ran a few tests, checking `bufferedAmount()` after every call to `dc->send()`.
> 
>     * When sending just the "Hello" string, the bufferedAmount remained zero until the second the channel closed, it did not increase.
> 
>     * When sending audio (1kB binary), the bufferedAmount was zero initially but soon climbed all the way to 120k before the DataChannel closed.

Very interesting, so as you can see in the first case the network conditions and the remote peer allow to sustain the rate, whereas in the second case, it buffers up to 120 messages since the Data Channel may not transmit fast enough. In that case, you need to send less.

> There is no data being sent from the other side, so I'm fairly certain there is no problem with the client.

OK, then it looks like a bug with the SCTP layer, I'll have a better look at the log and try to reproduce.

**Comment by sriramsk1999** [comment] 2020-11-09 15:12
I have an update on this issue. I had my entire game loop inside the `dc->onOpen()` function, and I noticed that the datachannel would close around 2 minutes, even if I wasn't sending any data! After that, I moved my game loop out of the lambda function and there wasn't a problem sending data. Not sure if there's a bug here but this should be useful if someone makes the same mistake :)

**Comment by murat-dogan** [comment] 2020-11-09 16:35
Probably you are blocking thread.

**Comment by paullouisageneau** [comment] 2020-11-09 17:55
I haven't had time to look into it, but it seems you found the issue! Indeed, like @murat-dogan suggests, if you block the callback, it actually blocks the SCTP network thread, so the connection can't be kept alive, therefore it will be closed after a while.

**Comment by paullouisageneau** [comment] 2020-11-11 12:36
I'm closing this, please reopen if you encounter other issues when sending an important volume of messages.

**Comment by balidani** [comment] 2020-12-18 16:53
Hello!

I have a similar issue, and so far I was unable to figure out why so I'm commenting here. 

- I send a relatively large amount of data, about 64k every 50 milliseconds. 
- I see that the DataChannel send function is called, but on the client side (JavaScript), I never get the messages. 
- I can't see any errors. When I turn on logging in libdatachannel I see no messages. 
- I also don't see any UDP traffic on tcpdump after it hangs.
- I can also receive messages from the client, but somehow sending hangs. 
- I can't reproduce it 100% of the time, but sometimes it does get stuck. 
- I moved everything to a separate thread, all it does is picking the message up from a map and sending it. 
- There is some locking for using the map, but I doubt those are getting interlocked, the map is rarely (ie. every 50ms) written to. 

If you have any idea on what I might be doing wrong, it would be much appreciated! Thanks!

**Comment by paullouisageneau** [comment] 2020-12-18 17:02
@balidani Do you block a callback thread from libdatachannel at some point? Also, what value does `bufferedAmount()` reports?

**Comment by balidani** [comment] 2020-12-18 17:21
`bufferedAmount` fills up when it gets stuck. I set a limit of 64k so if it's over 64k I don't send anything, but transmission seems to get stuck before this.

I don't block any of the callbacks on `DataChannel`, I even tried removing most of the code from `onMessage` to ignore incoming messages but nothing changed. The other callbacks `onOpen`, `onClosed` are basically empty. In PeerConnection I have `onStateChange` and `onGatheringStateChange`, these are empty, and `onDataChannel` is just setting up the DataChannel callbacks.

**Comment by murat-dogan** [comment] 2020-12-18 17:50
I can send large amount of data without any problem.
For a long time with a high rate.
I am sending messages as string. 
Are you sending as binary or string?

**Comment by balidani** [comment] 2020-12-18 19:04
I'm sending binary data, but I thought that should not matter based on other issues I've read? I put a message in `usrsctp_sendv` and that is also not called when `DataChannel` send fails. I'm not sure how I could see if a thread is blocked without me knowing. Maybe in gdb but my gdb-fu is not that strong so I will go see if it's possible.

**Comment by balidani** [comment] 2020-12-18 23:55
It looks like one of the threads that hang from the libdatachannel code is waiting here:
https://github.com/paullouisageneau/libdatachannel/blob/2d403247fb98fc7699874edbdd3403c47eda03c4/src/threadpool.cpp#L69

I *think* this thread is not hanging when sending works correctly, I see the thread is running in htop in those cases.

**Comment by paullouisageneau** [comment] 2020-12-20 20:54
@balidani The debugging seems pretty spot on! 

When the user sends at too high rate, SCTP refuses to send because its internal send buffer is full, then libdatachannel queues the message and waits for a flush, triggered either by `SCTP_EVENT_WRITE` from upcall or by `SCTP_SENDER_DRY_EVENT` from notifications.

It seems these events are not coming as expected, probably due to a subtle threading issue with usrsctp, since your example relies on a sending thread rather than leveraging `onBufferedAmountLow`.

Could you please try a simple mitigation: adding a call to `safeFlush()` at the end of `send()`?

**Comment by balidani** [comment] 2020-12-21 21:50
Thank you very much! That made everything much much more reliable. I think I saw a freeze once, but wasn't able to reproduce it in over 100 attempts. This is the diff in case anyone might need it:

```
diff --git a/src/sctptransport.cpp b/src/sctptransport.cpp
index af61ea2..69bdcc8 100644
--- a/src/sctptransport.cpp
+++ b/src/sctptransport.cpp
@@ -280,19 +280,22 @@ void SctpTransport::shutdown() {
 }
 
 bool SctpTransport::send(message_ptr message) {
-       std::lock_guard lock(mSendMutex);
+       {
+               std::lock_guard lock(mSendMutex);
 
-       if (!message)
-               return mSendQueue.empty();
+               if (!message)
+                       return mSendQueue.empty();
 
-       PLOG_VERBOSE << "Send size=" << message->size();
+               PLOG_VERBOSE << "Send size=" << message->size();
 
-       // If nothing is pending, try to send directly
-       if (mSendQueue.empty() && trySendMessage(message))
-               return true;
+               // If nothing is pending, try to send directly
+               if (mSendQueue.empty() && trySendMessage(message))
+                       return true;
 
-       mSendQueue.push(message);
-       updateBufferedAmount(uint16_t(message->stream), long(message_size_func(message)));
+               mSendQueue.push(message);
+               updateBufferedAmount(uint16_t(message->stream), long(message_size_func(message)));
+       }
+       safeFlush();
        return false;
 }
 ```

**Comment by paullouisageneau** [comment] 2020-12-24 15:02
I made fix here: https://github.com/paullouisageneau/libdatachannel/pull/298
It's similar except it tries to flush the current queue before attempting to send the new message, which keeps the buffered amount consistent.

**Closed** 2020-12-24 16:12 UTC
