### ISSUE TITLE
How to disable openssl/GnuTLS functionality from libdatachannel

### ISSUE THREAD

**Issue by fengshangren** [paullouisageneau/libdatachannel#713] opened 2022-08-31 06:51 UTC
Hi, I am trying to disable openssl/GnuTLS functionality from libdatachannel. Can someone help with information.

**Comment by paullouisageneau** [comment] 2022-08-31 11:09
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/399

**Comment by paullouisageneau** [comment] 2022-08-31 11:11
There is no option to disable the security layer, however you may find some information in https://github.com/paullouisageneau/libdatachannel/issues/399

**Closed** 2022-09-15 09:05 UTC
Labels: duplicate, wontfix
