### ISSUE TITLE
Add ICE candidate with public IP without STUN

### ISSUE THREAD

**Issue by LeoNavel** [paullouisageneau/libdatachannel#436] opened 2021-06-03 12:02 UTC
We are using libdatachannel on server with known public IP address. Is it possible to add this IP into ICE candidates in offer without using STUN?

**Comment by paullouisageneau** [comment] 2021-06-03 13:14
If you don't specify a STUN server to libdatachannel, on your server, it will only generate ICE host candidates for your server's interfaces. It's possible that your server has multiple interfaces, in that case, you can set `rtc::Configuration::bindAddress` to specify the public interface to use.

**Comment by michal-tomlein** [comment] 2021-06-10 14:58
Thank you for the response, but what we’re looking for is a way to bind the socket to 0.0.0.0 (the default), but replace the default candidate IP (the local IP of the network interface) with the server’s public IP. When we set `bindAddress` to the public IP, the socket fails to bind. Is this a use case you’d be interested in supporting?

**Comment by paullouisageneau** [comment] 2021-06-11 06:08
@michal-tomlein OK, I didn't understand your actual use case. You mean the server is behind a NAT, right? Do you forward the entire UDP port range to the server?

**Comment by michal-tomlein** [comment] 2021-06-11 06:56
Ours is not behind a NAT, it is an AWS Fargate task with a public IP, but yes, a server behind a NAT or load balancer with the entire port range forwarded could be another valid use case for this.

For us, the problem is that our public IP does not end up in the SDP offer. The private IP does, but we don’t want that address listed as a candidate at all.

**Comment by michal-tomlein** [comment] 2021-06-11 07:00
I should note that it does work with STUN, of course, but given that we know the public IP in advance, it seems unnecessary to involve another service in obtaining it.

**Comment by paullouisageneau** [comment] 2021-06-11 07:11
It's not only a matter of knowing the public address though, but also about the UDP ports being redirected to the private IP.

If the entire port range is redirected, you indeed don't need STUN, and there is a pretty easy fix: you may just manually replace the private IP address with the public one in the candidate before sending it through signaling, it will work fine.

**Comment by michal-tomlein** [comment] 2021-06-11 08:09
That was my original plan, just thought I’d ask before resorting to string manipulation. Thanks!

**Comment by paullouisageneau** [comment] 2021-06-29 20:16
I'm closing this, please reopen if needed.

**Closed by paullouisageneau** 2021-06-29 20:16 UTC
