### ISSUE TITLE
Test fails: TCP connect: Connection to localhost:48080 failed

### ISSUE THREAD

**Issue by yurivict** [paullouisageneau/libdatachannel#500] opened 2021-10-11 15:11 UTC
```
*** Running WebSocketServer test...
2021-10-11 08:09:46.252 DEBUG [212416] [rtc::impl::TcpServer::TcpServer@35] Initializing TCP server
2021-10-11 08:09:46.252 DEBUG [212416] [rtc::impl::TcpServer::listen@100] Listening on port 48080
2021-10-11 08:09:46.252 DEBUG [212416] [rtc::impl::Certificate::Generate@223] Generating certificate (OpenSSL)
2021-10-11 08:09:46.252 INFO  [220165] [rtc::impl::WebSocketServer::runLoop@67] Starting WebSocketServer
2021-10-11 08:09:46.252 DEBUG [212416] [rtc::impl::TcpTransport::TcpTransport@41] Initializing TCP transport
2021-10-11 08:09:46.252 DEBUG [212416] [rtc::impl::TcpTransport::start@76] Starting TCP recv thread
2021-10-11 08:09:46.253 DEBUG [220166] [rtc::impl::TcpTransport::connect@127] Connecting to localhost:48080
2021-10-11 08:09:46.253 DEBUG [220166] [rtc::impl::TcpTransport::connect@170] Trying address 127.0.0.1:48080
2021-10-11 08:09:46.253 WARN  [220166] [rtc::impl::TcpTransport::connect@151] TCP connection to 127.0.0.1:48080 failed, errno=61
2021-10-11 08:09:46.253 ERROR [220166] [rtc::impl::TcpTransport::runLoop@307] TCP connect: Connection to localhost:48080 failed
2021-10-11 08:09:46.253 DEBUG [220141] [rtc::impl::TcpTransport::stop@84] Waiting for TCP recv thread
2021-10-11 08:09:56.375 DEBUG [212416] [rtc::impl::WebSocketServer::stop@61] Stopping WebSocketServer thread
2021-10-11 08:09:56.375 DEBUG [212416] [rtc::impl::TcpServer::close@92] Closing TCP server socket
2021-10-11 08:09:56.375 DEBUG [220165] [rtc::impl::TcpServer::accept@85] TCP server closed
2021-10-11 08:09:56.375 INFO  [220165] [rtc::impl::WebSocketServer::runLoop@88] Stopped WebSocketServer
WebSocketServer test failed: WebSocket is not open
*** Error code 255
```

Version: 0.15.3
OS: FreeBSD 13

**Comment by paullouisageneau** [comment] 2021-10-11 15:14
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/454

**Closed as completed** 2021-10-11 15:15 UTC
Labels: duplicate

**Comment by yurivict** [comment] 2021-10-11 15:32
Sorry for reopening the same issue.

I've put a note into the FreeBSD port that dual stack is required to run tests.
