### ISSUE TITLE
Datachannel Reliability

### ISSUE THREAD

**Issue by murat-dogan** [paullouisageneau/libdatachannel#25] opened 2019-12-20 06:58 UTC
If one side of communication ended or terminated, the other side still sends messages without any error, state is still connected. 
About 5 min later state changes to disconnected.

You can make a test like that;
* Start tests/p2p apps.
* Make a connection
* Send some message
* Terminate one side
* Continue to send messages from other side
* It will send without any error
* Wait until state=disconnected message

**Comment by paullouisageneau** [comment] 2019-12-20 12:24
It's the expected behavior if you terminate one of the processes without closing the connection. Since the sender can't know the receiver left, the send method can't report an error synchronously.

However, a 5 min timeout seems indeed way too long. Some SCTP default timer might be the cause of this, I'm looking into it.

**Comment by murat-dogan** [comment] 2019-12-20 13:57
Behavior is  same even if you close connection respectively from one side and then terminate.

**Comment by paullouisageneau** [comment] 2019-12-20 14:22
OK then something is not working, I'll look into it.

**Closed** 2019-12-20 23:01 UTC
Labels: bug
