### ISSUE TITLE
Clarification about peerConnection states

### ISSUE THREAD

**Issue by slonv23** [paullouisageneau/libdatachannel#131] opened 2020-07-22 19:11 UTC
Hi, when I updated to the latest version of libdatachannel my code stopped to work as expected. I cannot close peerConnection after DISCONNECTED state was triggered. Here is my code:
```
    this->peerConnection->onStateChange([this](State state) {
        spdlog::debug("ClientConnection: Peer connection state: {}", utils::toString<State>(state));
        if ((state == State::Disconnected) || (state == State::Failed)) {
            spdlog::debug("Close method called!");
            this->peerConnection->close();
            spdlog::debug("PeerConnection closed!");
        } else if (state == State::Closed) {
            this->closed = true;
            if (this->closedCallback) {
                this->closedCallback();
            }
        }
    });
```
The problem is `PeerConnection closed!` is never printed, but `Close method called!` does.
Maybe something has changed and I don't need to call `peerConnection->close()` method anymore? Is DISCONNECTED equals CLOSED state now?

**Comment by paullouisageneau** [comment] 2020-07-22 19:42
I think that might be linked to the fact all callbacks are now asynchronous for the sake of consistency.

Before, calling `close()` whould result in the state change callback to be called immediately in the thread calling `close()`. This could lead to issues for instance a mutex locked twice by the same thread, etc.

Now, when `close()` is called, the state change is scheduled to be called by another thread. All callbacks now behave this way.

Could it explain the behavior difference in your case?

**Comment by slonv23** [comment] 2020-07-22 20:20
@paullouisageneau 
I turned on verbose logging and it seems that `peerConnection->close()` method called twice:
```
2020-07-22 20:17:18.735 INFO  [53144] [rtc::DtlsTransport::runRecvLoop@216] DTLS closed
2020-07-22 20:17:18.735 INFO  [53144] [rtc::SctpTransport::incoming@308] SCTP disconnected
2020-07-22 20:17:18.735 VERB  [53144] [rtc::PeerConnection::close@59] Closing PeerConnection
[2020-07-22 20:17:18.735] [debug] ClientConnection: Peer connection state: disconnected
[2020-07-22 20:17:18.735] [debug] Close method called!
2020-07-22 20:17:18.735 VERB  [53129] [rtc::PeerConnection::close@59] Closing PeerConnection
```
Maybe `peerConnection->close()` method is called somewhere internally when state changed to DISCONNECTED and I don't need to call it manually?

**Comment by paullouisageneau** [comment] 2020-07-22 20:43
The only thing calling `close()` internally would be the destructor. However, I guess `this->peerConnection` in your code is a shared pointer so you might call it somewhere else. My guess would be that a data channel closing also triggers the `peerConnection->close()` somehow in your code, so the first call to close is waiting for the data channel to close, and the data channel is waiting for a second call for the peer connection to close, which is blocked by the first one, hence a deadlock...

In your case it seems safe to drop the call to `close()` from the state change callback.

**Comment by slonv23** [comment] 2020-07-23 05:58
@paullouisageneau I found that I call `peerConnection->close()` method in `dataChannel->onClosed` callback. Thank you for help, I think I know how to fix it.

**Comment by slonv23** [comment] 2020-07-23 14:02
@paullouisageneau 
I have removed second call to `peerConnection->close()`. I still trying to close peerConnection when the DISCONNECTED state is triggered. But my onStateChange callback not called with the CLOSED state. Here what I see in logs:
```
2020-07-23 13:54:28.767 VERB  [8794] [rtc::IceTransport::LogCallback@267] juice: agent.c:431: No more datagrams to receive
2020-07-23 13:54:28.767 VERB  [8794] [rtc::IceTransport::LogCallback@267] juice: agent.c:387: Setting select timeout to 10000 ms
2020-07-23 13:54:28.767 DEBUG [8800] [rtc::DtlsTransport::runRecvLoop@202] DTLS connection cleanly closed
2020-07-23 13:54:28.767 VERB  [8800] [rtc::IceTransport::send@170] Send size=31
2020-07-23 13:54:28.768 INFO  [8800] [rtc::DtlsTransport::runRecvLoop@216] DTLS closed
2020-07-23 13:54:28.768 INFO  [8800] [rtc::SctpTransport::incoming@308] SCTP disconnected
[2020-07-23 13:54:28.768] [debug] ClientConnection: Peer connection state: disconnected
2020-07-23 13:54:28.768 VERB  [8779] [rtc::PeerConnection::close@59] Closing PeerConnection
2020-07-23 13:54:28.769 VERB  [8779] [rtc::PeerConnection::closeTransports@440] Closing transports
2020-07-23 13:54:28.769 DEBUG [8779] [rtc::SctpTransport::shutdown@259] SCTP shutdown
2020-07-23 13:54:28.769 VERB  [8779] [rtc::SctpTransport::handleWrite@526] Handle write, len=20
2020-07-23 13:54:28.769 VERB  [8779] [rtc::SctpTransport::handleWrite@526] Handle write, len=20
2020-07-23 13:54:28.770 INFO  [8779] [rtc::SctpTransport::shutdown@267] SCTP disconnected
2020-07-23 13:54:28.771 DEBUG [8779] [rtc::DtlsTransport::stop@109] Stopping DTLS recv thread
2020-07-23 13:54:28.771 VERB  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:117: Waiting for agent thread
2020-07-23 13:54:28.771 VERB  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:476: Interrupting agent thread
2020-07-23 13:54:28.771 WARN  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:491: Failed to interrupt thread by triggering socket, errno=99

```

**Comment by slonv23** [comment] 2020-07-23 14:04
I will try latest version and report than.

**Comment by slonv23** [comment] 2020-07-23 14:10
I have no issues with the latest version.

**Comment by paullouisageneau** [comment] 2020-07-23 14:50
OK perfect!

**Comment by slonv23** [comment] 2020-10-31 20:20
Hi! @paullouisageneau I have this issue again. Sometimes peerConnection state never changes from DISCONNECTED to  CLOSED and callback in onStateChange not executed. My code don't know that peerConnection cannot be used again and this cause 'DataChannel is closed' error. This happens maybe once every ten times. I pulled the latest version of the library.

> @paullouisageneau
> I have removed second call to `peerConnection->close()`. I still trying to close peerConnection when the DISCONNECTED state is triggered. But my onStateChange callback not called with the CLOSED state. Here what I see in logs:
> 
> ```
> 2020-07-23 13:54:28.767 VERB  [8794] [rtc::IceTransport::LogCallback@267] juice: agent.c:431: No more datagrams to receive
> 2020-07-23 13:54:28.767 VERB  [8794] [rtc::IceTransport::LogCallback@267] juice: agent.c:387: Setting select timeout to 10000 ms
> 2020-07-23 13:54:28.767 DEBUG [8800] [rtc::DtlsTransport::runRecvLoop@202] DTLS connection cleanly closed
> 2020-07-23 13:54:28.767 VERB  [8800] [rtc::IceTransport::send@170] Send size=31
> 2020-07-23 13:54:28.768 INFO  [8800] [rtc::DtlsTransport::runRecvLoop@216] DTLS closed
> 2020-07-23 13:54:28.768 INFO  [8800] [rtc::SctpTransport::incoming@308] SCTP disconnected
> [2020-07-23 13:54:28.768] [debug] ClientConnection: Peer connection state: disconnected
> 2020-07-23 13:54:28.768 VERB  [8779] [rtc::PeerConnection::close@59] Closing PeerConnection
> 2020-07-23 13:54:28.769 VERB  [8779] [rtc::PeerConnection::closeTransports@440] Closing transports
> 2020-07-23 13:54:28.769 DEBUG [8779] [rtc::SctpTransport::shutdown@259] SCTP shutdown
> 2020-07-23 13:54:28.769 VERB  [8779] [rtc::SctpTransport::handleWrite@526] Handle write, len=20
> 2020-07-23 13:54:28.769 VERB  [8779] [rtc::SctpTransport::handleWrite@526] Handle write, len=20
> 2020-07-23 13:54:28.770 INFO  [8779] [rtc::SctpTransport::shutdown@267] SCTP disconnected
> 2020-07-23 13:54:28.771 DEBUG [8779] [rtc::DtlsTransport::stop@109] Stopping DTLS recv thread
> 2020-07-23 13:54:28.771 VERB  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:117: Waiting for agent thread
> 2020-07-23 13:54:28.771 VERB  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:476: Interrupting agent thread
> 2020-07-23 13:54:28.771 WARN  [8779] [rtc::IceTransport::LogCallback@267] juice: agent.c:491: Failed to interrupt thread by triggering socket, errno=99
> ```

**Comment by slonv23** [comment] 2020-10-31 20:30
Here are some logs:
```
...
2020-10-31 20:27:24.793 VERB  [42214] [rtc::SctpTransport::send@282] Send size=136
2020-10-31 20:27:24.793 VERB  [42214] [rtc::SctpTransport::trySendMessage@358] SCTP try send size=136
2020-10-31 20:27:24.793 VERB  [42214] [rtc::SctpTransport::handleWrite@518] Handle write, len=164
2020-10-31 20:27:24.793 VERB  [42214] [rtc::DtlsTransport::send@123] Send size=164
2020-10-31 20:27:24.793 VERB  [42214] [rtc::IceTransport::send@213] Send size=193
2020-10-31 20:27:24.794 VERB  [42214] [rtc::SctpTransport::trySendMessage@413] SCTP sent size=136
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:419: Leaving select
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:446: Receiving datagrams
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:477: Received a datagram, size=57
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: stun.c:251: Not a STUN message: magic number invalid
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:496: Received a non-STUN datagram
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:1362: STUN selected entry matching incoming address
2020-10-31 20:27:25.010 VERB  [42752] [rtc::IceTransport::RecvCallback@283] Incoming size=57
2020-10-31 20:27:25.011 VERB  [42752] [rtc::DtlsTransport::incoming@142] Incoming size=57
2020-10-31 20:27:25.011 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:466: No more datagrams to receive
2020-10-31 20:27:25.011 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:586: STUN entry 0: Must be rearmed
2020-10-31 20:27:25.011 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:406: Setting select timeout to 10000 ms
2020-10-31 20:27:25.011 VERB  [42753] [rtc::SctpTransport::incoming@318] Incoming size=28
2020-10-31 20:27:25.011 VERB  [42753] [rtc::SctpTransport::handleSend@511] Handle send, free=1048576
2020-10-31 20:27:25.011 VERB  [42753] [rtc::SctpTransport::handleRecv@478] Handle recv, len=12
2020-10-31 20:27:25.011 VERB  [42753] [rtc::SctpTransport::processNotification@601] Processing notification, type=10
2020-10-31 20:27:25.011 VERB  [42753] [rtc::SctpTransport::processNotification@623] SCTP dry event
2020-10-31 20:27:25.053 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:419: Leaving select
2020-10-31 20:27:25.053 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:446: Receiving datagrams
2020-10-31 20:27:25.053 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:477: Received a datagram, size=31
2020-10-31 20:27:25.053 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: stun.c:251: Not a STUN message: magic number invalid
2020-10-31 20:27:25.053 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:496: Received a non-STUN datagram
2020-10-31 20:27:25.054 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:1362: STUN selected entry matching incoming address
2020-10-31 20:27:25.054 VERB  [42752] [rtc::IceTransport::RecvCallback@283] Incoming size=31
2020-10-31 20:27:25.054 VERB  [42752] [rtc::DtlsTransport::incoming@142] Incoming size=31
2020-10-31 20:27:25.054 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:466: No more datagrams to receive
2020-10-31 20:27:25.054 VERB  [42752] [rtc::IceTransport::LogCallback@310] juice: agent.c:406: Setting select timeout to 10000 ms
2020-10-31 20:27:25.054 DEBUG [42753] [rtc::DtlsTransport::runRecvLoop@201] DTLS connection cleanly closed
2020-10-31 20:27:25.054 VERB  [42753] [rtc::IceTransport::send@213] Send size=31
2020-10-31 20:27:25.054 INFO  [42753] [rtc::DtlsTransport::runRecvLoop@215] DTLS closed
2020-10-31 20:27:25.054 INFO  [42753] [rtc::PeerConnection::changeState@873] Changed state to disconnected
2020-10-31 20:27:25.054 INFO  [42753] [rtc::SctpTransport::incoming@312] SCTP disconnected
[2020-10-31 20:27:25.054] [debug] ClientConnection: Peer connection state: disconnected
2020-10-31 20:27:25.055 VERB  [42268] [rtc::PeerConnection::close@61] Closing PeerConnection
2020-10-31 20:27:25.055 VERB  [42753] [rtc::PeerConnection::close@61] Closing PeerConnection
2020-10-31 20:27:25.055 VERB  [42753] [rtc::PeerConnection::closeTransports@499] Closing transports
2020-10-31 20:27:25.055 INFO  [42753] [rtc::PeerConnection::changeState@873] Changed state to closed
2020-10-31 20:27:25.055 VERB  [42268] [rtc::PeerConnection::closeTransports@499] Closing transports
2020-10-31 20:27:25.055 DEBUG [42268] [rtc::SctpTransport::shutdown@263] SCTP shutdown
2020-10-31 20:27:25.056 VERB  [42268] [rtc::SctpTransport::handleWrite@518] Handle write, len=20
2020-10-31 20:27:25.056 VERB  [42268] [rtc::SctpTransport::handleWrite@518] Handle write, len=20
2020-10-31 20:27:25.056 INFO  [42268] [rtc::SctpTransport::shutdown@271] SCTP disconnected
2020-10-31 20:27:25.056 DEBUG [42268] [rtc::DtlsTransport::stop@113] Stopping DTLS recv thread
2020-10-31 20:27:25.056 VERB  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:117: Waiting for agent thread
2020-10-31 20:27:25.056 VERB  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:511: Interrupting agent thread
2020-10-31 20:27:25.056 WARN  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:526: Failed to interrupt thread by triggering socket, errno=99
[2020-10-31 20:27:25.116] [info] Received message from world-simulator-app with size: 134
[2020-10-31 20:27:25.116] [info] Broadcast
[2020-10-31 20:27:25.224] [error] Failed to process world-simulator-app message, error: DataChannel is closed
[2020-10-31 20:27:25.455] [info] Received message from world-simulator-app with size: 134
[2020-10-31 20:27:25.455] [info] Broadcast
[2020-10-31 20:27:25.455] [error] Failed to process world-simulator-app message, error: DataChannel is closed
[2020-10-31 20:27:25.794] [info] Received message from world-simulator-app with size: 134
[2020-10-31 20:27:25.794] [info] Broadcast
...
```

**Comment by slonv23** [comment] 2020-10-31 20:32
As you can see there is only one message about state change:
`[2020-10-31 20:27:25.054] [debug] ClientConnection: Peer connection state: disconnected`
This message is absent:
`[2020-10-31 20:27:25.054] [debug] ClientConnection: Peer connection state: closed`

**Comment by paullouisageneau** [comment] 2020-11-01 09:54
First, the PeerConnection seems to be closed twice. It should still work, but it's weird. According to the log, its state changes to closed but the callback is not called.
```
2020-10-31 20:27:25.055 INFO  [42753] [rtc::PeerConnection::changeState@873] Changed state to closed
```

What could happen is all threads of the threadpool being busy on something. Is it never called or is it still called after some time? Also, what OS do you use? This warning might explain why threads get stuck for a while:
```
2020-10-31 20:27:25.056 VERB  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:117: Waiting for agent thread
2020-10-31 20:27:25.056 VERB  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:511: Interrupting agent thread
2020-10-31 20:27:25.056 WARN  [42268] [rtc::IceTransport::LogCallback@310] juice: agent.c:526: Failed to interrupt thread by triggering socket, errno=99
```

**Comment by slonv23** [comment] 2020-11-01 21:22
@paullouisageneau Indeed, peerConnection was closed twice. Second time was in dataChannel->onClosed. I removed second call and now it seems to work without errors. I use windows, but my app runs in docker (debian buster container).

**Comment by slonv23** [comment] 2020-11-01 21:22
> Is it never called or is it still called after some time?
Never called.

**Comment by paullouisageneau** [comment] 2020-11-01 21:31
OK, then I think this is caused by the same problem again, two different callbacks trying to close at the same time so each one is waiting for the other to finish. I'll push a small fix to prevent this situation even if close is called multiple times.

**Closed** 2020-11-01 22:00 UTC
