### ISSUE TITLE
Build Issue 

### ISSUE THREAD

**Issue by tirthesh007** [paullouisageneau/libdatachannel#629] opened 2022-05-14 12:58 UTC
Hi @paullouisageneau ,
I have solved the Open SSL realated error using the steps suggested to write "FindOpenSSL.cmake" inside "/cmake/modules",
and now make file is successfull.
But now I am getting errors as below:

```
Tirthesh/libdatachannel/libdatachannel# make -j2
Consolidate compiler generated dependencies of target juice-static
Consolidate compiler generated dependencies of target usrsctp
[ 12%] Built target juice-static
[ 12%] Building C object deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o
Consolidate compiler generated dependencies of target srtp2
[ 12%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/srtp/srtp.c.o
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:424:7: error: implicit declaration of function 'getifaddrs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rc = getifaddrs(&ifas);
             ^
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:475:2: error: implicit declaration of function 'freeifaddrs' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        freeifaddrs(ifas);
        ^
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:475:2: note: did you mean 'getifaddrs'?
/home/Tirthesh/libdatachannel/libdatachannel/deps/usrsctp/usrsctplib/netinet/sctp_bsd_addr.c:424:7: note: 'getifaddrs' declared here
        rc = getifaddrs(&ifas);
             ^
2 errors generated.
deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/build.make:103: recipe for target 'deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o' failed
make[2]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/netinet/sctp_bsd_addr.c.o] Error 1
CMakeFiles/Makefile2:458: recipe for target 'deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all' failed
make[1]: *** [deps/usrsctp/usrsctplib/CMakeFiles/usrsctp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher.c.o
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/cipher_test_cases.c.o
[ 14%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/null_cipher.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_icm_ossl.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/cipher/aes_gcm_ossl.c.o
[ 16%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth.c.o
[ 17%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/auth_test_cases.c.o
[ 17%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/null_auth.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/hash/hmac_ossl.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/alloc.c.o
[ 19%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/crypto_kernel.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/err.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/kernel/key.c.o
[ 21%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/math/datatypes.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdb.c.o
[ 23%] Building C object deps/libsrtp/CMakeFiles/srtp2.dir/crypto/replay/rdbx.c.o
[ 23%] Linking C static library libsrtp2.a
[ 23%] Built target srtp2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

Can you please help me to solve this errors.

**Comment by paullouisageneau** [comment] 2022-05-14 17:35
Duplicate of https://github.com/paullouisageneau/libdatachannel/issues/595#issuecomment-1126710727

**Closed by paullouisageneau** 2022-05-14 17:35 UTC
Labels: duplicate
