### ISSUE TITLE
Exception thrown from rtc::impl::PeerConnection

### ISSUE THREAD

**Issue by hanseuljun** [paullouisageneau/libdatachannel#508] opened 2021-10-18 03:03 UTC
I have been using libdatachannel for iOS via your C API and found that the following happens when a user closes the app, which calls the destructors of instances in the "std::unordered_map"s at src/capi.cpp.

To provide more context, this happens when there is 1 PeerConnection in peerConnectionMap that has two dataChannels (one reliable and another unreliable) that would exist in dataChannelMap.

When a user closes the app, destructor of rtc::PeerConnection calls rtc::impl::PeerConnection::close, then rtc::impl::PeerConnection::~PeerConnection. The problem is, rtc::impl::PeerConnection::~PeerConnection gets called before rtc::impl::PeerConnection::close() is done.

When I modify code like below
<img width="515" alt="Screen Shot 2021-10-17 at 7 48 37 PM" src="https://user-images.githubusercontent.com/5001447/137661788-07a057e7-db80-4741-84de-50a9629a753d.png">

log like below appears
<img width="571" alt="Screen Shot 2021-10-17 at 7 49 28 PM" src="https://user-images.githubusercontent.com/5001447/137661839-84e92368-fe29-4d08-b93f-937404e05bad.png">

showing that the destructor gets called before finishing mProcessor->enqueue(&PeerConnection::closeDataChannels, this);. Then, the app crashes with the following error message:
terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument

Finally, thanks for reading. While I won't be able to try that until next weekend as I don't have access to a device causing this issue except for the weekends, I would be very happy to try out an idea that you think may remove this error.

**Comment by paullouisageneau** [comment] 2021-10-18 11:32
> The problem is, rtc::impl::PeerConnection::~PeerConnection gets called before rtc::impl::PeerConnection::close() is done.

I don't think that's exactly what happens here. `PeerConnection` calls `impl::PeerConnection::close`, then `impl::PeerConnection::~PeerConnection`. `impl::PeerConnection` is held by a `shared_ptr`, so there is no way another thread calls `impl::PeerConnection::~PeerConnection` before the call to `close` is finished, as `PeerConnection` still holds the `shared_ptr` during the call. Therefore, I think the only scenario where the sequence can happen is that `mProcessor->enqueue()` itself throws the exception, then `impl::PeerConnection::~PeerConnection` is called as it should while the exception goes up the stack.

The exception means a recursive mutex has been destroyed prior to an attempt at locking it. The only recusive mutex in the `mProcessor->enqueue()` callee tree is `Init::Mutex`. Therefore, this looks like a global destruction order issue (global destruction order being undefined in C++ is really a pain) where `Init::Mutex` is destroyed before `peerConnectionMap` for C API.

I think the culprit is `Init` implementation here, I'll look into it.

**Comment by paullouisageneau** [comment] 2021-10-18 14:17
This should be fixed with https://github.com/paullouisageneau/libdatachannel/pull/509

**Comment by paullouisageneau** [comment] 2021-10-18 19:11
Please re-open if the problem is not solved. Thank you for reporting!

**Closed as completed by paullouisageneau** 2021-10-18 19:11 UTC
Labels: bug

**Comment by hanseuljun** [comment] 2021-10-18 19:18
This was really quick! Thanks so much!! I won't be able to test this thing (I saw this happen only when using a iPhone 12 mini and closing the app in a specific way) in a week but will come back in case there still is an issue!
