### ISSUE TITLE
Multiple DataChannels (FireFox & Libdatachannel)

### ISSUE THREAD

**Issue by sashabjorkman** [paullouisageneau/libdatachannel#541] opened 2022-01-17 16:35 UTC
While doing FireFox to libdatachannel communication, a "bug" happens causing libdatachannel to be flooded with stream reset events.
This happens if either:
1) FireFox has more than 1 datachannels on the peerconnection.
2) Libdatachannels has more than 2 datachannels on the peerconnection.

I am not sure if this is just intended behavior and that multiple datachannels are just not supported (_yet?_) with libdatachannel. Or if maybe I am doing something wrong with negotiation. Or if this maybe has already been fixed in some dev branch.

I managed to replicate the issue by cloning the master branch of libdatachannel. Inside of `examples/web/script.js` I add: `pc.createDataChannel(label+'2')`  to the offerPeerConnection function. Then I start the signaling server as per usual. And then I run the examples/client with log level Verbose (but Debug will also show the problem). If the web client creates an offer to the server the following is spammed over and over again to the terminal of the native client: [error.txt](https://github.com/paullouisageneau/libdatachannel/files/7883410/error.txt)
What is stranger is that despite the reset events being spammed, data seems to still be transferable.

This "error" is probably already known, but I thought it might be worth reporting just in case.

With my limited knowledge of WebRTC (after reading the libdatachannel source code, which is beautiful BTW) I believe it is Firefox (and Chrome according to my tests) that is sending out these stream events, but I know too little about WebRTC to understand why. I have tried setting the bundle policy to max-bundle but that doesn't help. Either way, this isn't anything that hinders me from using the library since I'll just combine all of my datachannel into one on an application level instead. As such, thank you for putting your time and effort into this project :).

**Comment by paullouisageneau** [comment] 2022-01-18 10:57
Thank you for reporting! This is actually a bug caused by libdatachannel closing the Data Channel by resetting the stream on any invalid message, including attempts to close a non-existing Data Channel. This may lead to both peers ping-ponging close messages about an already destroyed Data Channel.

For information, the line at issue is:
 https://github.com/paullouisageneau/libdatachannel/blob/41df4b513d9b514e8644d47fb73e1506f0d51abe/src/impl/peerconnection.cpp#L435

Your example triggers the situation not because there are multiple Data Channels, but because the example client stores the second Data Channel in place of the first one at reception, so the first one will be destroyed immediately.

I think the bug was overlooked until now because apart from the debug log, there seems to be no other apparent symptom. Good catch :+1:

**Closed** 2022-01-18 11:14 UTC
Labels: bug
