### ISSUE TITLE
Adoption hinderance

### ISSUE THREAD

**Issue by rokups** [paullouisageneau/libdatachannel#557] opened 2022-02-15 08:19 UTC
Hello there,
I wanted to voice some gripes i am having. Let me start with how i ended up here. Me with some friends were looking to rework networking in a game engine we maintain. Our main issue with current networking was no support in web builds. WebRTC is an obvious answer here. So we started looking and we find libdatachannel. Code is simply put perfect, i would go as far as call it a work of art. Small enough, yet does everything we need and even allows getting rid of things we do not (media). Unfortunately we can not use it. It all boils down to the license. In order to abide by LGPL license, games would have to build library as a dynamic library. That is fine for the desktop (mostly). It would rule out fully static builds though, it means linux builds would have to be dynamic, with all the issues of making such application working across myriad of linux distributions. Well its linux, small market share, hobbyist games, who cares, right? They can bear the weight. However we just can not say the same for iOS. Apple simply does not allow dynamic libraries on  App Store. Logic of this is beyond me, but that hardly matters as we must abide by the rules if we want to deploy anything on App Store. So to abide by LGPL license and deploy to App Store (i think) users would have to provide re-linkable object files for users to be able to rebuild the application. But they would not be able to run such application then, so i wonder if object file availability would even be enough to satisfy the license. It also is a whole new requirement passed down on to users and i would argue it is quite not trivial to handle, compared to dynamic builds on linux. And then we have web builds, which are basically static. So the only way to really abide by the license on the web is to release source code with a compatible license. Our game engine is licensed under MIT and we want our users to be able to do do as they wish with their creations, therefore forcing a certain license on certain platforms is really not an option. Well we are just a few hobbyists making another irrelevant game engine. I do realize what we do is mostly irrelevant and nobody should care much about that, its just few people having fun and learning something in the process. However I myself happen work on a software close to gamedev world and i happen to know a little bit how wheels of those companies turn. It can take a significant time for a legal department to give an OK on a license used by a particular software, however they immediately veto anything that has GPL in the license. In the end, any GPL license of a library severely limits ability to use that library. I can understand why PyQt uses GPL - they sell commercial licenses and this is their business model, which is perfectly fine thing to do. In case of libdatachannel i do not quite understand motivation behind using LGPL, as it only restricts usability of the library, without offering anything in return for the author (as far as i can see commercial licenses are not offered). I am not asking to change a license though, i do realize it is an unreasonable request from a stranger on the internet. I just wanted to point out a situation that stems from the license. I guess i can add one last thing: at my current job i am working on a MIT-licensed software that is given away freely and is used widely by many game development studios. It is not like everyone took our code and ran away because it was not under lock of GPL. On the contrary - they pay us for maintenance and support, because they prefer someone else to do the hard work for them, and who is a better option than official maintainers.

That is a lot of text. Since you got through it all, thank you for your patience, suffering through my frustrated rambling.

**Comment by Calinou** [comment] 2022-05-19 19:30
Since there are only 31 contributors as of writing (some of them who may not have copyrightable contributions), it may be a good idea to look into relicensing libdatachannel under MPL 2.0.

**Comment by alephzero** [comment] 2022-08-17 05:19
+1 I am also blocked based on license.

**Comment by rokups** [comment] 2022-08-17 05:41
Anyone affected may find QUIC protocol interesting. It offers UDP in the browser as well, but adoption is still in early days. microsoft/msquic is a viable solution for C++ applications to utilize this protocol.

**Comment by paullouisageneau** [comment] 2022-09-02 19:20
@rokups Thank you for the feedback. You seem to only consider such a decision in terms of personal gain, and through that lens, you are right that it doesn't make sense. If personal gain was my goal here, I wouldn't have made the library open source, I guess I would have created a company to commercialize a proprietary SDK. To answer your interrogations, the decision is actually political: I believe that permissive open-source, by fostering proprietization, has mostly become a way for companies distributing closed-source software to massively profit from a benevolent workforce while stifling users' freedoms. Therefore I prefer copyleft free software licenses like the GPL which somehow better ensure the freedoms of end users by guaranteeing the right to access the modified source code. In the end, I think it boils down to different definitions of what freedom is or different levels of importance given to these matters, but to me granting the ability to restrict the rights of others is not something desirable. I know very well a lot of companies veto anything GPL-licensed. That's by design.

However, I admit the LGPL introduces a practical issue for shipping to Apple devices as the very restrictive ToS of the App store conflict with GPL licenses. I don't use Apple products nor develop for them, so it's not something I considered.

Anyway, after some discussions over email and Discord, it seems the blocking point is the difficulty to bundle the library into closed-source apps, even the impossibility to do so in the case of the App store. The MPL 2.0, as @Calinou suggested, looks like a good compromise here: it would allow this use case while still being a weak copyleft license compatible with the GPL. What do you think?

**Comment by rokups** [comment] 2022-09-03 08:06
It indeed boils down to one's definition of 'freedom'. Developers are your users, they deserve some kind of freedom as well. MPL sounds like a perfect compromise as it would both keep project open and yet not infect downstream projects with a mandatory license change. Thank you for considering it :pray:

**Comment by paullouisageneau** [comment] 2022-10-13 08:42
Closing as re-licensing process is initiated in https://github.com/paullouisageneau/libdatachannel/issues/728.

**Closed by paullouisageneau** 2022-10-13 08:42 UTC

**Comment by rokups** [comment] 2023-09-20 12:24
Hey @paullouisageneau i would like to once again thank you for going through the trouble and relicensing this wonderful project. This allowed our [hobby project](https://github.com/rbfx/rbfx) to switch to libdatachannel as a network backend and now we have networking functionality in web builds. This feature was wished for for many years. Thank you for enabling us to have networked fun from the browser as well! 🙏
