### ISSUE TITLE
Often, MediaTrack cannot start as intended: Consent expired for candidate pair

### ISSUE THREAD

**Issue by chobie** [paullouisageneau/libdatachannel#1006] opened 2023-10-18 12:57 UTC
I'm playing media transmission feature on my custom binding side.
It seems that there are often instances where it doesn't connect well with Chrome.

As for the phenomenon, the logs indicate that the Track is open, but media data cannot be sent. (On Chrome's chrome://webrtc-internals, the statistics for inbound-rtp don't increase.)
Also, it gets disconnected after 30 seconds due to 'Consent expired'. 

I suspect there might be an issue with the DTLS-SRTP transport, but I'm unsure where to start troubleshooting. 
Since this is related to my custom binding, I feel hesitant to raise an issue, but if you have any ideas or hints, please let me know. maybe I was simply using it incorrectly.

Environment:
  network: local network (127.0.0.1)
  sender: Mac M1 (libdatachannel + (Go binding / my Unity binding))
    https://github.com/chobie/datachannel-go/blob/main/examples/opus_sender/main.go#L392
  receiver: Mac M1(same pc) Chrome. (https://github.com/chobie/datachannel-go/blob/main/examples/html_opus_receiver/index.html)
  stun: not set
  reproduce : about 50%?
  api: CAPI
  build: `cmake -B build -DUSE_GNUTLS=0 -DUSE_NICE=0 -DCMAKE_BUILD_TYPE=Release`
  
these are excerpted DEBUG log.

```
4 rtc::impl::PeerConnection::initDtlsTransport@253: This connection requires media support
5 rtc::impl::DtlsTransport::DtlsTransport@733: Initializing DTLS transport (OpenSSL)
5 rtc::impl::DtlsSrtpTransport::DtlsSrtpTransport@68: Initializing DTLS-SRTP transport
5 rtc::impl::DtlsTransport::start@837: Starting DTLS transport
4 rtc::impl::IceTransport::LogCallback@362: juice: Changing state to completed
4 rtc::impl::PeerConnection::changeIceState@1197: Changed ICE state to completed
4 rtc::impl::DtlsTransport::doRecv@960: DTLS handshake finished
4 rtc::impl::DtlsSrtpTransport::postHandshake@301: Deriving SRTP keying material (OpenSSL)
5 rtc::impl::DtlsSrtpTransport::postHandshake@307: SRTP profile is: SRTP_AEAD_AES_256_GCM
4 rtc::impl::PeerConnection::changeState@1179: Changed state to connected
```

It seems track opened. but actually not connected correctly.
client -> chrome rtp packet does not arrived.
(The log is the same up to this point even when it connects normally.)

after 30 seconds.  disconnected automatically.

```
4 rtc::impl::IceTransport::LogCallback@362: juice: STUN entry 0: Consent expired for candidate pair
3 rtc::impl::IceTransport::LogCallback@362: juice: Lost connectivity
4 rtc::impl::IceTransport::LogCallback@362: juice: Changing state to failed
4 rtc::impl::PeerConnection::changeIceState@1197: Changed ICE state to failed
4 rtc::impl::PeerConnection::changeState@1179: Changed state to failed
StateChanged 4
4 rtc::impl::PeerConnection::changeIceState@1197: Changed ICE state to closed
4 rtc::impl::PeerConnection::changeState@1179: Changed state to closed
StateChanged 5
TrackClosed
5 rtc::impl::DtlsTransport::stop@860: Stopping DTLS transport
4 rtc::impl::DtlsTransport::doRecv@992: DTLS closed
5 rtc::impl::DtlsTransport::stop@860: Stopping DTLS transport
5 rtc::impl::DtlsTransport::stop@860: Stopping DTLS transport
5 rtc::impl::DtlsTransport::~DtlsTransport@831: Destroying DTLS transport
5 rtc::impl::IceTransport::~IceTransport@159: Destroying ICE transport
```

**Comment by chobie** [comment] 2023-10-18 17:40
Oh, I'm sorry. I figured it out myself. 

When I was casually observing packets with WireShark, I noticed that when the connection was unsuccessful, an ICMPv6 "Destination Unreachable" message appeared. 

<img width="1025" src="https://github.com/paullouisageneau/libdatachannel/assets/195038/17a58fe3-72d1-4d35-9e75-1d7e4fce64bd">

When adding the "addIceCandidate" on the HTML side, I added a process to exclude it if it's IPv6, and the issue of not being able to connect was resolved.

```
--- a/web/audio.html
+++ b/web/audio.html
@@ -97,10 +97,13 @@
                             break;

                         case 'candidate':
-                            pc.addIceCandidate({
-                                candidate : message.candidate,
-                                sdpMid : message.mid,
-                            });
+                            const ipv6Regex = /([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}/;
+                            if (!ipv6Regex.test(message.candidate)) {
+                                pc.addIceCandidate({
+                                    candidate : message.candidate,
+                                    sdpMid : message.mid,
+                                    });
+                            }
                             break;
                         }
                     }
```

canadidate message is like this.
```
{"id":"bZih","type":"candidate","candidate":"candidate:2 1 UDP 2130706175 2405:6580:b220:7100:180a:fcbf:92c9:e557 51972 typ host","mid":"1"}
```


For future reference, could you advise on the preferred way to handle this? If an IPv6 address is presented as an ICE candidate and a connection can't be established, how should one respond?

**Comment by paullouisageneau** [comment] 2023-10-20 23:57
Here it looks look like the connection could be established over the IPv6 candidate pair, otherwise it would have used IPv4. The issue is that IPv6 connectivity was then seemingly lost. 

ICE forbids gathering candidates for localhost (for instance 127.0.0.1 or ::1), as a result the connections is established over local interface addresses, and I have already observed broken connectivity on MacOS on CI tests, sadly I can't reproduce myself.

libjuice has a build flag `ENABLE_LOCAL_ADDRESS_TRANSLATION` to mitigate such issues, you should try to enable it: https://github.com/paullouisageneau/libjuice/blob/95caecd0af669fbe7ffa91fbaf2b788e9d76dee1/CMakeLists.txt#L18

**Comment by chobie** [comment] 2023-10-27 02:09
I tried setting it to `ENABLE_LOCAL_ADDRESS_TRANSLATION` for about a week. I believe the connection issue with MediaTrack has been alleviated since it was able to connect in most cases.

There are still some cases where it cannot connect, but I think that's an issue with the local development environment. 

for now, by ensuring that I don't send signaling when the `rtcSetLocalCandidateCallback` contains an ipv6 candidate, I've been able to address this issue.

```C#
peer.OnLocalCandidate = (peer, canadidate, mid) =>
{
    Debug.Log("OnLocalCandidate");

    if (!ContainsIPv4(canadidate))
    {
        // don't send info to signaling server when canadidate contains ipv6 address.
        return;
    }

    var dict = new JSONObject();
    dict["id"] = new JSONString(peer.Id);
    dict["type"] = new JSONString("candidate");
    dict["candidate"] = new JSONString(canadidate);
    dict["mid"] = new JSONString(mid);

    webSocket.Send(dict.ToString());
};
```

I think it's okay to close this Issue.

**Comment by paullouisageneau** [comment] 2023-10-27 08:08
Thank you for the follow-up. I'm closing this, please reopen if needed.

**Closed by paullouisageneau** 2023-10-27 08:08 UTC
