### ISSUE TITLE
Tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [paullouisageneau/libdatachannel#424] opened 2021-05-16 20:48 UTC
```
$ ./work/.build/tests-0.13.0 

*** Running WebRTC connectivity test...
2021-05-16 13:47:08.847 DEBUG [100981] [rtc::InitLogger@82] Logger initialized
2021-05-16 13:47:08.847 DEBUG [100981] [rtc::Init::Init@129] Global initialization
2021-05-16 13:47:08.853 DEBUG [102452] [rtc::impl::@197] Generating certificate (OpenSSL)
2021-05-16 13:47:08.853 DEBUG [102228] [rtc::impl::@197] Generating certificate (OpenSSL)
2021-05-16 13:47:08.853 DEBUG [100981] [rtc::impl::IceTransport::IceTransport@58] Initializing ICE transport (libjuice)
2021-05-16 13:47:08.853 INFO  [100981] [rtc::impl::IceTransport::IceTransport@106] Using STUN server "stun.ageneau.net:3478"
2021-05-16 13:47:08.853 DEBUG [100981] [rtc::impl::PeerConnection::processLocalDescription@837] Adding application to local description, mid="0"
Description 1: 2021-05-16 13:47:08.854 INFO  [100981] [rtc::impl::PeerConnection::changeSignalingState@1065] Changed signaling state to new
2021-05-16 13:47:08.854 INFO  [100981] [rtc::impl::PeerConnection::changeGatheringState@1054] Changed gathering state to in-progress
v=0
o=rtc 3689070831 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
a=setup:actpass
a=ice-ufrag:YW3U
a=ice-pwd:GNt4rIJXuYhrfhC+wx57L2
a=ice-options:trickle
a=fingerprint:sha-256 38:4B:98:73:0C:0E:9C:33:66:C4:BD:D7:34:28:53:08:F8:59:93:02:7F:03:B9:69:DD:B2:BE:D9:DF:31:E1:C1
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=bundle-only
a=mid:0
a=sendrecv
a=sctp-port:5000
a=max-message-size:1048576

2021-05-16 13:47:08.854 INFO  [100981] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to gathering
2021-05-16 13:47:08.854 DEBUG [102452] [rtc::impl::IceTransport::IceTransport@58] Initializing ICE transport (libjuice)
2021-05-16 13:47:08.854 INFO  [102452] [rtc::impl::IceTransport::IceTransport@106] Using STUN server "stun.ageneau.net:3478"
2021-05-16 13:47:08.854 INFO  [102452] [rtc::impl::PeerConnection::changeSignalingState@1065] Changed signaling state to new
Signaling state 2: have-remote-offer
2021-05-16 13:47:08.854 DEBUG [102452] [rtc::impl::PeerConnection::processLocalDescription@772] Reciprocating application in local description, mid="0"
2021-05-16 13:47:08.854 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to connecting
Description 2: 2021-05-16 13:47:08.856 INFO  [102452] [rtc::impl::PeerConnection::changeSignalingState@1065] Changed signaling state to new
v=0
o=rtc 4280351944 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
a=setup:active
a=ice-ufrag:tpya
a=ice-pwd:idjr0SDV+j3Ahoyaj9R71R
a=ice-options:trickle
a=fingerprint:sha-256 7B:1D:C2:BE:1C:85:C5:19:2E:3A:ED:F6:47:55:0E:06:7F:47:BF:6B:5E:61:AD:FB:E5:97:68:98:88:A7:01:96
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=bundle-only
a=mid:0
a=sendrecv
a=sctp-port:5000
a=max-message-size:1048576

2021-05-16 13:47:08.856 INFO  [102680] [rtc::impl::PeerConnection::changeState@1037] Changed state to connecting
2021-05-16 13:47:08.856 INFO  [102452] [rtc::impl::PeerConnection::changeGatheringState@1054] Changed gathering state to in-progress
2021-05-16 13:47:08.856 INFO  [102452] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to gathering
Signaling state 1: have-local-offer
Gathering state 1: in-progress
Candidate 1: a=candidate:1 1 UDP 2122317823 192.168.5.3 42124 typ host
2021-05-16 13:47:08.856 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to connecting
2021-05-16 13:47:08.857 INFO  [103215] [rtc::impl::PeerConnection::changeState@1037] Changed state to connecting
2021-05-16 13:47:08.857 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:604: Using STUN server stun.ageneau.net:3478
2021-05-16 13:47:08.858 WARN  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:08.858 WARN  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:1521: STUN message send failed, errno=22
2021-05-16 13:47:08.858 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:824: STUN server binding failed (timeout)
2021-05-16 13:47:08.858 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:2187: Candidate gathering done
2021-05-16 13:47:08.858 INFO  [102680] [rtc::impl::PeerConnection::changeGatheringState@1054] Changed gathering state to complete
2021-05-16 13:47:08.858 WARN  [102228] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:08.858 WARN  [102228] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:757: Failed to interrupt thread by triggering socket, errno=22
2021-05-16 13:47:08.858 INFO  [102228] [rtc::impl::PeerConnection::changeSignalingState@1065] Changed signaling state to connecting
Signaling state 2: stable
Gathering state 2: in-progress
Candidate 2: a=candidate:1 1 UDP 2122317823 192.168.5.3 5548 typ host
2021-05-16 13:47:08.858 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:604: Using STUN server stun.ageneau.net:3478
2021-05-16 13:47:08.858 WARN  [102228] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:08.858 WARN  [102228] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:757: Failed to interrupt thread by triggering socket, errno=22
State 2: connecting
2021-05-16 13:47:08.858 WARN  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:08.858 WARN  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:1521: STUN message send failed, errno=22
2021-05-16 13:47:08.858 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:824: STUN server binding failed (timeout)
2021-05-16 13:47:08.858 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:2187: Candidate gathering done
2021-05-16 13:47:08.858 INFO  [103215] [rtc::impl::PeerConnection::changeGatheringState@1054] Changed gathering state to complete
Gathering state 2: complete
2021-05-16 13:47:08.858 WARN  [102452] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:08.858 WARN  [102452] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:757: Failed to interrupt thread by triggering socket, errno=22
State 1: connecting
Gathering state 1: complete
Signaling state 1: stable
2021-05-16 13:47:18.863 WARN  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:18.863 WARN  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:1521: STUN message send failed, errno=22
2021-05-16 13:47:18.863 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:830: Candidate pair check failed (timeout)
2021-05-16 13:47:18.867 WARN  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:18.867 WARN  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:1521: STUN message send failed, errno=22
2021-05-16 13:47:18.867 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:830: Candidate pair check failed (timeout)
2021-05-16 13:47:18.905 INFO  [100981] [rtc::impl::PeerConnection::changeState@1037] Changed state to closed
State 2: closed
2021-05-16 13:47:18.905 WARN  [102452] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
2021-05-16 13:47:18.905 WARN  [102452] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:757: Failed to interrupt thread by triggering socket, errno=22
2021-05-16 13:47:18.905 INFO  [100981] [rtc::impl::PeerConnection::changeState@1037] Changed state to closed
State 1: closed
WebRTC connectivity test failed: 2021-05-16 13:47:18.905 WARN  [101952] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:420: Send failed, errno=22
PeerConnection is not connected
2021-05-16 13:47:18.905 WARN  [101952] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:757: Failed to interrupt thread by triggering socket, errno=22
2021-05-16 13:47:28.863 INFO  [103215] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to disconnected
2021-05-16 13:47:28.877 INFO  [102680] [rtc::impl::IceTransport::LogCallback@339] juice: agent.c:768: Changing state to disconnected
```

Also, could you please add a section to README how to run tests. Both ```test``` and ```tests``` targets don't run them.

OS: FreeBSD 12.2

**Comment by paullouisageneau** [comment] 2021-05-17 07:39
I don't think libjuice has been tested on FreeBSD yet. It seems the `sendto` requires mapping IPv4 to IPv6 when the socket is IPv6, like other non-Linux OS. It should be fixed with https://github.com/paullouisageneau/libjuice/pull/93.

**Closed** 2021-05-17 07:55 UTC

**Comment by paullouisageneau** [comment] 2021-05-17 08:00
libjuice has been updated in https://github.com/paullouisageneau/libdatachannel/commit/76d9ce5ba3fa67c278e941dfdfc69e609ff4717b, you'll need to update submodules to pull the fix.

Please re-open if the issue isn't correctly fixed for you.

**Comment by yurivict** [comment] 2021-05-17 16:34
The ```tests-0.13.0``` executable now runs, thanks.

What is the target to run tests?

```make test``` or ```make tests``` don't run them.

**Comment by paullouisageneau** [comment] 2021-05-17 17:05
This is no target created by cmake to run tests for now. You may simply run `tests` in the build directory.
